name: flutter-version-number
description: "Reads the version number of the pubspec.yaml"
author: NiklasLehnfeld
branding:
  icon: "archive"
  color: "green"
inputs:
  file-path:
    description: "Path to your pubspec.yaml. Default is ./pubspec.yaml"
    required: false
    default: "./pubspec.yaml"
outputs:
  version-number:
    description: "Version number"
    value: ${{ steps.read-yaml.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: read-yaml
      run: |
        VERSION=`cat ${{inputs.file-path}} | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs`
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      shell: bash
