name: some_app
description: Some strange flutter app

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0
  json_annotation: ^4.1.0
  http: ^0.13.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


